version: "2"

services:
    redis-master:
        image: "bitnami/redis:latest"
        expose:
            - "6379"
        environment:
            - REDIS_REPLICATION_MODE=master
            - REDIS_PASSWORD=my_master_password

    redis-replica-1:
        image: "bitnami/redis:latest"
        expose:
            - "6379"
        depends_on:
            - redis-master
        environment:
            - REDIS_REPLICATION_MODE=slave
            - REDIS_MASTER_HOST=redis-master
            - REDIS_MASTER_PORT_NUMBER=6379
            - REDIS_MASTER_PASSWORD=my_master_password
            - REDIS_PASSWORD=my_replica_password

    redis-replica-2:
        image: "bitnami/redis:latest"
        expose:
            - "6379"
        depends_on:
            - redis-master
        environment:
            - REDIS_REPLICATION_MODE=slave
            - REDIS_MASTER_HOST=redis-master
            - REDIS_MASTER_PORT_NUMBER=6379
            - REDIS_MASTER_PASSWORD=my_master_password
            - REDIS_PASSWORD=my_replica_password

    redis-replica-3:
        image: "bitnami/redis:latest"
        expose:
            - "6379"
        depends_on:
            - redis-master
        environment:
            - REDIS_REPLICATION_MODE=slave
            - REDIS_MASTER_HOST=redis-master
            - REDIS_MASTER_PORT_NUMBER=6379
            - REDIS_MASTER_PASSWORD=my_master_password
            - REDIS_PASSWORD=my_replica_password

    redis-replica-4:
        image: "bitnami/redis:latest"
        expose:
            - "6379"
        depends_on:
            - redis-master
        environment:
            - REDIS_REPLICATION_MODE=slave
            - REDIS_MASTER_HOST=redis-master
            - REDIS_MASTER_PORT_NUMBER=6379
            - REDIS_MASTER_PASSWORD=my_master_password
            - REDIS_PASSWORD=my_replica_password
