version: "3"

services:
    wp:
        container_name: wp_ricardogottheil
        image: wordpress:latest # https://hub.docker.com/_/wordpress/
        ports:
            - 81:80 # change ip if required
        volumes:
            - ./config/php.conf.uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
            - ricardogottheil_front_data:/var/www/html # Full wordpress project
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_NAME: "${DB_NAME}"
            WORDPRESS_DB_USER: root
            WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD}"
            VIRTUAL_PORT: 81
        depends_on:
            - db

    db:
        container_name: db
        image: mysql:latest
        ports:
            - 3306:3306
        command:
            [
                "--default_authentication_plugin=mysql_native_password",
                "--character-set-server=utf8mb4",
                "--collation-server=utf8mb4_unicode_ci",
            ]
        volumes:
            - ./wp-data:/docker-entrypoint-initdb.d
            - ricardogottheil_db_data:/var/lib/mysql
        environment:
            MYSQL_DATABASE: "${DB_NAME}"
            MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    nginx:
        image: nginx:1.15-alpine
        container_name: nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./data/nginx:/etc/nginx/conf.d
            - ricardogottheil_front_data:/var/www/html:rw
            - ./letsencrypt/conf:/etc/letsencrypt
    certbot:
        container_name: certbot
        image: certbot/certbot
        volumes:
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot

    letsencrypt:
        restart: always
        image: vdhpieter/letsencrypt-webroot
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /var/run/docker.sock:/var/run/docker.sock
            - ./letsencrypt/conf:/etc/letsencrypt
            - ./letsencrypt/html:/tmp/letsencrypt
            - ricardogottheil_front_data:/var/www/html
        links:
            - nginx
        environment:
            - DOMAINS=mcmagna.com www.mcmagna.com
            - EMAIL=rgotthei@eafit.edu.co
            - WEBROOT_PATH=/var/www/html
            - EXP_LIMIT=30
            - CHECK_FREQ=30
            - CHICKENEGG=1
            - STAGING=0

    volumes:
        ricardogottheil_db_data:
        ricardogottheil_front_data:
